# Splunk UF: forward to indexer
# Place in: C:\Program Files\SplunkUniversalForwarder\etc\system\local\outputs.conf

[tcpout]
defaultGroup = indexer_group

[tcpout:indexer_group]
server = <SPLUNK_INDEXER_IP>:9997

[tcpout-server://<SPLUNK_INDEXER_IP>:9997]
