index=wineventlog OR index=windows EventCode=4625
| eval IpAddress = coalesce(IpAddress, src_ip, src)
| bin _time span=5m
| stats count by TargetUserName, IpAddress, Host, _time, FailureReason
| where count >= 5
| table _time Host TargetUserName IpAddress count FailureReason
